### ISSUE TITLE
Link find should try where the user is first

### ISSUE THREAD

**Issue by henriklovhaug** [henriklovhaug/md-cli#1]

**Comment by Areskiko** [comment]
Jump to first occurrence in the user's view

**Comment by Fildor** [comment]
Just to recap how I understand the question:

We have something like ...

```
[Some Link Number 1](http://domain.com/resouce.html)

["Position" or Cursor is here]: #

[Some Link Number 2](someOtherTarget)
```
And question is: should Link1 or Link2 be selected first? Is that correct?

Assuming correct, I (_personal **opinion**_) would probably expect Link 2 to be selected first and then "modulo" back to the first in view for subsequent calls.

_Except_ if there were two different Key-Maps for "Find" and "Find next". If only one Key-Map, then I would expect the described behavior. 

**But:** I really do not think it matters _that_ much. Just pick the one that's reasonable to you (again: imho).

Regards, Fil

**Comment by henriklovhaug** [comment]
As _cursor_ is not a concept in this TUI yet (todo?), the only reference points for a user is where on the screen or in the document the link selection should start from. So currently I see two possible options: top of the screen, and middle of the screen.
